import { getPRDiff, postPRComment, formatReviewComment } from "../services/githubService.js";
import { processDiff } from "../services/diffService.js";
import { reviewCode, generatePRSummary } from "../services/aiReviewService.js";
import { createTokenTracker } from "../utils/tokenCounter.js";

export async function handlePRWebhook(req, res) {
  const event = req.headers["x-github-event"];

  if (event !== "pull_request") {
    return res.status(200).send("Event ignored");
  }

  const { action, pull_request, repository } = req.body;

  if (action !== "opened" && action !== "synchronize") {
    return res.status(200).send("Event ignored");
  }

  const repo     = repository.full_name;
  const prNumber = pull_request.number;

  res.status(200).json({ message: "Review started", repo, prNumber });

  const tokens = createTokenTracker();

  try {
    console.log(`🔍 Reviewing PR #${prNumber} in ${repo}...`);

    const diff = await getPRDiff(repo, prNumber);

    // 1. Generate PR summary + track tokens
    const rawSummary = await generatePRSummary(diff, { repo, prNumber });
    const prSummary  = Array.isArray(rawSummary) ? rawSummary : [];
    tokens.trackSummary(diff, JSON.stringify(prSummary));
    console.log(`📋 PR summary generated`);

    if (prSummary.length > 0) {
      const summaryComment = [
        `## 📋 MergeMind — PR Summary`,
        ``,
        prSummary.map(bullet => `- ${bullet}`).join("\n"),
        ``,
        `> 🤖 Generated by MergeMind · ${new Date().toISOString().slice(0, 10)}`,
      ].join("\n");

      await postPRComment(repo, prNumber, summaryComment);
      console.log(`✅ Summary posted to ${repo}#${prNumber}`);
    } else {
      console.warn(`⚠️ Summary was empty, skipping summary comment`);
    }

    // 2. Review chunks + track tokens per chunk
    const chunks = processDiff(diff);
    console.log(`📦 ${chunks.length} chunk(s) to review`);

    const reviews = [];
    for (let index = 0; index < chunks.length; index++) {
      console.log(`  → Chunk ${index + 1}/${chunks.length}`);
      const result = await reviewCode(chunks[index], { repo, prNumber, chunkIndex: index });
      tokens.trackChunk(index, chunks[index], result);
      reviews.push(result);
    }

    // 3. Print token report to console
    console.log(tokens.formatReport());

    // 4. Get token totals to append to the review comment
    const tokenReport = tokens.getReport();

    const reviewComment = formatReviewComment(reviews, {
      repo,
      prNumber,
      reviewedAt: new Date().toISOString(),
      prSummary,
      tokenReport,
    });

    await postPRComment(repo, prNumber, reviewComment);
    console.log(`✅ Review posted to ${repo}#${prNumber}`);

  } catch (error) {
    console.error(`❌ Review failed for ${repo}#${prNumber}:`, error.message);
    console.log(tokens.formatReport()); // print even on failure
  }
}