import { getPRDiff, postPRComment, formatReviewComment } from "../services/githubService.js";
import { processDiff } from "../services/diffService.js";
import { reviewCode, generatePRSummary } from "../services/aiReviewService.js";

export async function handlePRWebhook(req, res) {
  const event = req.headers["x-github-event"];

  if (event !== "pull_request") {
    return res.status(200).send("Event ignored");
  }

  const { action, pull_request, repository } = req.body;

  if (action !== "opened" && action !== "synchronize") {
    return res.status(200).send("Event ignored");
  }

  const repo = repository.full_name;
  const prNumber = pull_request.number;

  res.status(200).json({ message: "Review started", repo, prNumber });

  try {
    console.log(`🔍 Reviewing PR #${prNumber} in ${repo}...`);

    const diff = await getPRDiff(repo, prNumber);

    // 1. Generate and post PR summary as its own comment
    const prSummary = await generatePRSummary(diff, { repo, prNumber });
    console.log(`📋 PR summary generated`);

    const summaryComment = [
      `## 📋 MergeMind — PR Summary`,
      ``,
      prSummary.map(bullet => `- ${bullet}`).join("\n"),
      ``,
      `> 🤖 Generated by MergeMind · ${new Date().toISOString().slice(0, 10)}`,
    ].join("\n");

    await postPRComment(repo, prNumber, summaryComment);
    console.log(`✅ Summary posted to ${repo}#${prNumber}`);

    // 2. Review chunks and post full review as a second comment
    const chunks = processDiff(diff);
    console.log(`📦 ${chunks.length} chunk(s) to review`);

    const reviews = [];
    for (let index = 0; index < chunks.length; index++) {
      console.log(`  → Chunk ${index + 1}/${chunks.length}`);
      const result = await reviewCode(chunks[index], { repo, prNumber, chunkIndex: index });
      reviews.push(result);
    }

    const reviewComment = formatReviewComment(reviews, {
      repo,
      prNumber,
      reviewedAt: new Date().toISOString(),
      prSummary,
    });

    await postPRComment(repo, prNumber, reviewComment);
    console.log(`✅ Review posted to ${repo}#${prNumber}`);

  } catch (error) {
    console.error(`❌ Review failed for ${repo}#${prNumber}:`, error.message);
  }
}